# Generated by Django 4.0 on 2021-12-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='map',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
