# Generated by Django 4.0 on 2021-12-23 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0005_job_map_alter_job_location_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
