# Generated by Django 4.0 on 2021-12-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='like',
        ),
    ]
